import { Briefcase } from "lucide-react"
import { defineField, defineType } from "sanity"

export const project = defineType({
  name: "project",
  title: "Project",
  type: "document",
  icon: Briefcase,
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "casestudy", title: "Case study" },
    { name: "media", title: "Media" },
    { name: "settings", title: "Settings" },
  ],
  fields: [
    defineField({
      name: "client",
      title: "Client",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "title",
      title: "Project name / headline",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "client", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "type",
      title: "Type",
      type: "string",
      group: "content",
      description: 'Short descriptor shown as an eyebrow, e.g. "Growing business-management application".',
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "reference",
      to: [{ type: "category" }],
      group: "content",
      options: { filter: 'appliesTo match "project"' },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "industry",
      title: "Industry",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      group: "content",
      description: 'e.g. "Active partnership", "Completed"',
    }),
    defineField({
      name: "year",
      title: "Year",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "completionDate",
      title: "Completion date",
      type: "date",
      group: "content",
      options: { dateFormat: "MMMM YYYY" },
    }),
    defineField({
      name: "website",
      title: "Client website",
      type: "url",
      group: "content",
    }),
    defineField({
      name: "summary",
      title: "Summary",
      type: "text",
      rows: 3,
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "services",
      title: "Technologies / Services used",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
      options: { layout: "tags" },
    }),
    defineField({
      name: "overview",
      title: "Overview",
      type: "text",
      rows: 4,
      group: "casestudy",
    }),
    defineField({
      name: "challenge",
      title: "Challenge",
      type: "text",
      rows: 4,
      group: "casestudy",
    }),
    defineField({
      name: "strategy",
      title: "Solution / Approach",
      type: "text",
      rows: 4,
      group: "casestudy",
    }),
    defineField({
      name: "results",
      title: "Results",
      type: "array",
      of: [{ type: "resultItem" }],
      group: "casestudy",
    }),
    defineField({
      name: "cover",
      title: "Cover image",
      type: "image",
      group: "media",
      options: { hotspot: true },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      group: "media",
    }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      group: "settings",
      initialValue: false,
    }),
    defineField({
      name: "order",
      title: "Display order",
      type: "number",
      group: "settings",
      initialValue: 0,
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "settings",
    }),
  ],
  orderings: [
    { title: "Display order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] },
    { title: "Newest", name: "yearDesc", by: [{ field: "year", direction: "desc" }] },
  ],
  preview: {
    select: { title: "client", subtitle: "title", media: "cover" },
  },
})
